feat: Extend workflowstates
ISDuBA/ISDuBA pull request #145
Opened 2024-05-29 12:17 UTC by ThomasJunk

Extend the given workflowstates with the backward paths from the `Admin`.

2024-05-29 14:44 UTC, s-l-teichmann commented
No. E.g.  `{ReadWorkflow, DeleteWorkflow}:        {Editor, Reviewer},` Editors should not be allowed to move documents to the delete state. only Reviewers should be able to do so.

2024-05-30 06:12 UTC, ThomasJunk commented
My bad, I took it from [main](https://github.com/ISDuBA/ISDuBA/blob/main/pkg/models/workflow.go#L47) without checking it.

2024-05-30 10:44 UTC, s-l-teichmann requested changes

2024-05-30 10:44 UTC, s-l-teichmann commented on client/src/lib/permissions.ts
I think the matrix in the client should be machine generated to have a the single source of truth.

2024-06-03 10:22 UTC, s-l-teichmann approved these changes
From my side this done now. -> LGTM

2024-06-03 10:34 UTC, JanHoefelmeyer approved these changes
LGTM & works

2024-06-03 11:51 UTC, merged