Add initial downloader
ISDuBA/ISDuBA pull request #180
Opened 2024-06-18 15:04 UTC by koplas

This draft explores what changes to `csaf_distribution` are needed to use it as a library for this project. Currently, it crashes because `LogLevel` can't be set.

Changes needed:
- [ ] Make `options.LogLevel` visible
- [ ] Implement an alternative of `options.Parser`
- [ ] Allow to log in to io.Writer or implement different logging method

2024-07-02 10:12 UTC, JanHoefelmeyer requested changes
A few initial things that bothered me:
- [ ] setup scripts no longer work and no documentation on how to fix
- [x] everyone can access sources tab and create (but not save) jobs, should be disabled for everyone but importer/source-manager
- [x] given "start job" and "delete job" are right next to each other, I'd prefer a warning if you want to delete it
- [ ] editing a job resets several values: start and end date, the three checkboxes at the bottom, client key and passphrase unless they are explicitly saved via the browser (which is the wrong way to handle this, for multiple reasons)
- [ ] start and end ranges using MM/DD/YYYY is inconsistent with the downloader using YYYY-MM-DD
- [x] tasks can be clicked, but clicking them doesn't do anything
- [x] all job logs are simply dumped into the repository's main directory. 
- [x] When starting a job, status doesn't update itself on completion (but it does upon refresh, site reload, abortion etc.)
- [x] aborted job will be shown as completed upon refresh
- [ ] schedules cannot be edited. Would expect a similar method to jobs.

- [ ] idea: job name, schedule name and cron expression show example values. These could be pre-entered(, with the name schema: 'Schedule #X', X∈ℕ, X being the smallest nontaken number and the cron expression either being the one used on the last created cron job with the shown expression as default or with a configurable default)

 - [ ] input-fields need to check whether their input is valid. Some try to do so, but aren't perfect (e.g. number of workers only accepts integers, but accepts all from ℤ, not only ℕ), some fail completely and accept any input.

I will keep checking for a bit, but those were the first few things I found.

2024-07-04 10:37 UTC, cintek commented
>   everyone can access sources tab and create (but not save) jobs, should be disabled for everyone but importer/source-manager

Fixed.

>   given "start job" and "delete job" are right next to each other, I'd prefer a warning if you want to delete it

Now we show a warning and the icon buttons are a bit larger so it's easier to hit them.

>  start and end ranges using MM/DD/YYYY is inconsistent with the downloader using YYYY-MM-DD

I think this is okay because they are different applications. Also, we'd have to create a new component (as far as I remember the options) just to change the order of day, month, and year. That's much effort for very little improvement.

>  tasks can be clicked, but clicking them doesn't do anything

Now the cursor is no pointer anymore when hovering the tasks.

>  When starting a job, status doesn't update itself on completion (but it does upon refresh, site reload, abortion etc.)

Now the task list will be updated every minute.

>  input-fields need to check whether their input is valid.

This is definitively on our TODO list.

2024-07-04 12:30 UTC, koplas commented on pkg/importer/scheduler.go
> +}
Replace all locks with waiting for all goroutines to finish. There is a race condition while closing the database connection while the download handler still uses it.

2024-07-04 12:32 UTC, koplas commented on pkg/web/sources.go
> +	}
Duplicate code in `addJob`. Change the behavior of `updateJob` or refactor it into a separate function.

2024-07-04 12:35 UTC, koplas commented on pkg/web/sources.go
> +	}
Missing validation. This will only result in errors while running a task and not before configuration.

2024-07-09 11:39 UTC, koplas commented on .gitmodules
> +	url = git@github.com:csaf-poc/csaf_distribution.git
This will be removed, when a new `csaf_distribution` version is released.

2024-07-29 11:40 UTC, koplas commented
This implementation no longer fits the requirements.

2024-07-29 11:40 UTC, closed without merging