Add Reuse action, update licenses, make reuse compliant
ISDuBA/ISDuBA pull request #26
Opened 2024-03-04 10:34 UTC by JanHoefelmeyer

Contributes to https://github.com/ISDuBA/ISDuBA/issues/16

2024-03-06 14:35 UTC, bernhardreiter commented
merge the current state of main in, remove the unrelated chance and then commit.

2024-03-06 14:36 UTC, bernhardreiter requested changes

2024-03-06 14:36 UTC, bernhardreiter commented on docs/scripts/configurekeycloak.sh
this change seems unrelated to the reuse action, should be removed

2024-03-07 10:31 UTC, JanHoefelmeyer commented on docs/scripts/configurekeycloak.sh
Seems to have been a mistake anyway, so removed.

2024-03-07 16:49 UTC, bernhardreiter approved these changes

2024-03-07 16:50 UTC, merged