Allow drag and drop in query overview
ISDuBA/ISDuBA pull request #309
Opened 2024-08-12 15:00 UTC by koplas

2024-08-13 11:24 UTC, s-l-teichmann requested changes

2024-08-13 11:24 UTC, s-l-teichmann commented on pkg/web/queries.go
> +	err := ctx.Request.ParseMultipartForm(1000 * 1000)
Maybe it is a better idea to pass a JSON document to this endpoint.

2024-08-13 11:24 UTC, s-l-teichmann commented on pkg/web/queries.go
> +	updateSQL := `UPDATE stored_queries SET num = ( CASE`
This generated case feels a bit tricky. I would prefer a transaction running a batch update in it.

2024-08-14 10:44 UTC, s-l-teichmann requested changes

2024-08-14 10:44 UTC, s-l-teichmann commented on pkg/web/queries.go
> +func (c *Controller) updateOrder(ctx *gin.Context) {
Almost ... (untested)
```Go
func (c *Controller) updateOrder(ctx *gin.Context) {
	type queryOrder struct {
		ID    int64 `json:"id"`
		Order int64 `json:"order"`
	}
	var orders []queryOrder
	if err := ctx.ShouldBindJSON(&orders); err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	const (
		prefix   = `UPDATE stored_queries SET num = $2 WHERE id = $1 AND `
		adminSQL = prefix + `(definer = $3 OR global)`
		userSQL  = prefix + `definer = $3`
	)
	var updateSQL string
	if c.hasAnyRole(ctx, models.Admin) {
		updateSQL = adminSQL
	} else {
		updateSQL = userSQL
	}

	batch := &pgx.Batch{}
	definer := ctx.GetString("uid")
	for _, order := range orders {
		batch.Queue(updateSQL, order.ID, order.Order, definer)
	}

	if err := c.db.Run(
		ctx.Request.Context(),
		func(rctx context.Context, conn *pgxpool.Conn) error {
			tx, err := conn.Begin(rctx)
			if err != nil {
				return err
			}
			defer tx.Rollback(rctx)
			if err := tx.SendBatch(rctx, batch).Close(); err != nil {
				return err
			}
			return tx.Commit(rctx)
		}, 0,
	); err != nil {
		slog.Error("database error", "err", err)
		ctx.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
	}
}

```

2024-08-16 10:31 UTC, cintek approved these changes
LGTM & works

2024-08-16 10:32 UTC, merged