WIP: Forwarder
ISDuBA/ISDuBA pull request #483
Opened 2024-10-10 14:34 UTC by koplas

Adds an initial forwarder.

2024-10-19 08:55 UTC, s-l-teichmann requested changes
`docs/isdubad-config.md` needs a new `forwarder` section.

2024-10-22 12:37 UTC, s-l-teichmann requested changes

2024-10-22 12:37 UTC, s-l-teichmann commented on pkg/forwarder/forwarder.go
> +func (fm *ForwardManager) fetchValidationStatus(ctx context.Context, documentID int64) validationStatus {
Could be moved into the statement in loadDocument. To do so just create the SQL statement with the  `sb.WhereClause` from the SQLBuilder and not `.CreateQuery`

2024-10-23 10:51 UTC, JanHoefelmeyer approved these changes
LGTM & works

2024-10-23 14:01 UTC, s-l-teichmann approved these changes

2024-10-23 14:01 UTC, merged