feat: Add SSVC validation in client
ISDuBA/ISDuBA pull request #736
Opened 2024-12-05 16:26 UTC by cintek

Solves #711.

2024-12-10 06:11 UTC, JanHoefelmeyer requested changes
Opening the SSVC dialogue:
Uncaught (in promise) TypeError: date is undefined
    isDateValid SSVCInput.svelte:50
    validateVector SSVCInput.svelte:44
    instance SSVCInput.svelte:31
    run utils.js:41
    mount_component Component.js:47
    flush scheduler.js:99

2024-12-13 08:57 UTC, cintek commented
Current state: When @JanHoefelmeyer is testing the PR and he pastes a SSVC into the input it isn't validated right away. Only if he moves the cursor within the field or enters a character. I cannot reproduce the issue. What is expected is that the validation starts even if a value was only pasted and no further interaction was made and when I test this it works as expected.

2025-01-02 12:03 UTC, cintek commented
The problem was that @JanHoefelmeyer used the mouse button to paste the value but it wasn't recognized as expected. This should be fixed now.

2025-01-02 15:36 UTC, JanHoefelmeyer approved these changes
LGTM & works

2025-01-02 15:36 UTC, merged